### 1. Import Libraries

In [2]:
import pandas as pd

### 2. Load and Consolidate Data

In [3]:
# Define the path to the processed files
file_path = f'../../data/processed/'

leptospirosis_processed = pd.read_csv(f"{file_path}1_leptospirosis_processed.csv")
climatic_processed = pd.read_csv(f"{file_path}2_climatic_processed.csv")
agriculture_processed = pd.read_csv(f"{file_path}3_agriculture_processed.csv")
socioeconomic_processed = pd.read_csv(f"{file_path}4_socioeconomic_processed.csv")

In [4]:
climatic_processed

,District,YearMonth,Precipitation_mm,Temp_Min_C,Temp_Max_C,Soil_Moisture_0_7cm,Year,Month
0,Ampara,2007-01,144.799990,20.800500,28.350500,0.361118,2007,1
1,Ampara,2007-02,30.300001,19.600500,30.150500,0.328018,2007,2
2,Ampara,2007-03,17.900000,19.800500,31.900500,0.242438,2007,3
3,Ampara,2007-04,201.800000,23.600500,31.950499,0.347476,2007,4
4,Ampara,2007-05,71.100000,24.450500,33.900497,0.319367,2007,5
...,...,...,...,...,...,...,...,...
5395,Vavuniya,2024-08,150.200010,23.175999,37.426003,0.278938,2024,8
5396,Vavuniya,2024-09,26.500000,23.925999,37.776000,0.169007,2024,9
5397,Vavuniya,2024-10,220.800000,22.925999,35.776000,0.326785,2024,10
5398,Vavuniya,2024-11,494.400020,21.726000,32.576000,0.374460,2024,11
5399,Vavuniya,2024-12,186.199980,21.075998,30.376000,0.327636,2024,12

In [5]:
consolidated_dataframe = (leptospirosis_processed.merge(climatic_processed,on=["District","Month","Year"])
                                                 .merge(agriculture_processed,on=["District","Year"])
                                                 .merge(socioeconomic_processed,on=["District","Year"])
                                                )
consolidated_dataframe

,District,Month,Cases,Year,YearMonth,Precipitation_mm,Temp_Min_C,Temp_Max_C,Soil_Moisture_0_7cm,MRiceArea,MRiceYield,SRiceArea,SRiceYield,Population,Households,Avg_HH_Size
0,Ampara,1,0,2007,2007-01,144.799990,20.800500,28.350500,0.361118,"51,803","4,934","53,787","4,993",613439,149447,4.10
1,Anuradhapura,1,6,2007,2007-01,48.000000,18.678000,29.528000,0.286926,"57,562","4,726","14,635","4,804",822222,213995,3.84
2,Badulla,1,5,2007,2007-01,59.700000,15.911000,25.061000,0.438316,"22,266","4,434","10,705","4,639",792806,194099,4.08
3,Batticaloa,1,0,2007,2007-01,191.900000,21.300000,28.600000,0.317090,"18,469","2,891","2,705","3,680",500109,121907,4.10
4,Colombo,1,12,2007,2007-01,62.300003,20.311000,32.260998,0.199657,"3,354","3,033",879,"3,346",2303397,533606,4.32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5395,Polonnaruwa,12,73,2024,2024-12,304.500000,20.765501,31.665500,0.444524,"69,983",4697,"66,614",5716,447530,126482,3.54
5396,Puttalam,12,62,2024,2024-12,118.300000,21.371500,31.321500,0.306285,"20,652",3843,"16,094",3609,818816,231494,3.54
5397,Ratnapura,12,298,2024,2024-12,173.500000,20.358000,31.708000,0.442219,"12,930",4301,"10,331",4566,1145423,324853,3.53
5398,Trincomalee,12,25,2024,2024-12,217.200010,22.165000,30.915000,0.331133,"48,483",3409,"28,773",5053,442745,119351,3.71
5399,Vavuniya,12,21,2024,2024-12,186.199980,21.075998,30.376000,0.327636,"23,412",3878,"5,516",4175,172312,47825,3.60

### Save Processed Data
 - data\processed

In [6]:
##saved as a new csv
consolidated_dataframe[
    (consolidated_dataframe["Year"] != 2007)].drop(columns=["Avg_HH_Size"]).to_csv('../../data/processed/consolidated_dataframe.csv',
                index=False)